/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    profiles: Profile;
    favorites: Favorite;
    'listing-types': ListingType;
    cities: City;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    'listing-types': ListingTypesSelect<false> | ListingTypesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  profile?: (number | null) | Profile;
  avatarURL?: string | null;
  roles: ('organizer' | 'host' | 'provider' | 'client' | 'admin')[];
  status?: ('active' | 'pending' | 'suspended') | null;
  agreeTermsAndConditions: boolean;
  agreePrivacyPolicy: boolean;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  user: number | User;
  userType?: ('organizer' | 'host' | 'provider' | 'client')[] | null;
  /**
   * Full name or business name
   */
  name: string;
  /**
   * Profile avatar
   */
  avatar?: (number | null) | Media;
  /**
   * Display name
   */
  displayName?: string | null;
  /**
   * Short bio or tagline
   */
  bio?: string | null;
  /**
   * Primary contact number
   */
  phone?: string | null;
  /**
   * Personal or business website
   */
  website?: string | null;
  /**
   * Primary city of operation
   */
  city?: string | null;
  socialMedia?: {
    /**
     * Facebook profile/page URL
     */
    facebook?: string | null;
    /**
     * Instagram profile URL
     */
    instagram?: string | null;
    /**
     * LinkedIn profile URL
     */
    linkedin?: string | null;
    /**
     * YouTube channel URL
     */
    youtube?: string | null;
    /**
     * TikTok profile URL
     */
    tiktok?: string | null;
    /**
     * Twitch profile URL
     */
    twitch?: string | null;
    /**
     * X profile URL
     */
    x?: string | null;
  };
  verified?: {
    status?: ('none' | 'pending' | 'approved' | 'rejected') | null;
    documents?:
      | {
          type?: ('id' | 'company' | 'other') | null;
          file: number | Media;
          notes?: string | null;
          id?: string | null;
        }[]
      | null;
    verificationData?: {
      fullName?: string | null;
      address?: string | null;
      isCompany?: boolean | null;
      companyName?: string | null;
      cui?: string | null;
      companyAddress?: string | null;
    };
  };
  rating?: {
    average?: number | null;
    count?: number | null;
  };
  favorites?: (number | Favorite)[] | null;
  memberSince?: string | null;
  lastOnline?: string | null;
  views?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  user?: (number | null) | User;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-types".
 */
export interface ListingType {
  id: number;
  /**
   * URL-friendly identifier (e.g., logodna, sala-evenimente)
   */
  slug: string;
  /**
   * Display name (e.g., Logodnă, Sală de evenimente)
   */
  title: string;
  /**
   * Category header (e.g., NUNȚI & CEREMONII DE FAMILIE)
   */
  category: string;
  /**
   * Slugified category name
   */
  categorySlug: string;
  /**
   * Which taxonomy type this belongs to
   */
  type: 'events' | 'locations' | 'services';
  /**
   * Order within category (maintains the defined hierarchy)
   */
  sortOrder: number;
  /**
   * Whether this taxonomy item is active/available
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  /**
   * The official name of the city
   */
  name: string;
  /**
   * Auto-generated from city name. Used in URLs and lookups.
   */
  slug?: string | null;
  country?: string | null;
  /**
   * Where this city data originated from
   */
  source?: ('seeded' | 'google' | 'user') | null;
  /**
   * Geographic coordinates (latitude, longitude)
   *
   * @minItems 2
   * @maxItems 2
   */
  geo: [number, number];
  /**
   * Number of times this city is referenced
   */
  usageCount?: number | null;
  /**
   * Indicates if this city data has been verified by admins
   */
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null)
    | ({
        relationTo: 'listing-types';
        value: number | ListingType;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  profile?: T;
  avatarURL?: T;
  roles?: T;
  status?: T;
  agreeTermsAndConditions?: T;
  agreePrivacyPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  user?: T;
  userType?: T;
  name?: T;
  avatar?: T;
  displayName?: T;
  bio?: T;
  phone?: T;
  website?: T;
  city?: T;
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        youtube?: T;
        tiktok?: T;
        twitch?: T;
        x?: T;
      };
  verified?:
    | T
    | {
        status?: T;
        documents?:
          | T
          | {
              type?: T;
              file?: T;
              notes?: T;
              id?: T;
            };
        verificationData?:
          | T
          | {
              fullName?: T;
              address?: T;
              isCompany?: T;
              companyName?: T;
              cui?: T;
              companyAddress?: T;
            };
      };
  rating?:
    | T
    | {
        average?: T;
        count?: T;
      };
  favorites?: T;
  memberSince?: T;
  lastOnline?: T;
  views?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-types_select".
 */
export interface ListingTypesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  categorySlug?: T;
  type?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  source?: T;
  geo?: T;
  usageCount?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}