-- Temporarily convert to text so we can normalize values
ALTER TABLE "events" ALTER COLUMN "tier" SET DATA TYPE text;
-- Set all existing event tiers to the new default standard tier
UPDATE "events" SET "tier" = '06-standard';
DROP TYPE "public"."enum_events_tier";
CREATE TYPE "public"."enum_events_tier" AS ENUM('05-new', '06-standard', '02-headline', '03-spotlight', '04-recommended', '07-sponsored', '01-ambassador');
ALTER TABLE "events" ALTER COLUMN "tier" SET DATA TYPE "public"."enum_events_tier" USING "tier"::"public"."enum_events_tier";
ALTER TABLE "_events_v" ALTER COLUMN "version_tier" SET DATA TYPE text;
UPDATE "_events_v" SET "version_tier" = '06-standard';
DROP TYPE "public"."enum__events_v_version_tier";
CREATE TYPE "public"."enum__events_v_version_tier" AS ENUM('05-new', '06-standard', '02-headline', '03-spotlight', '04-recommended', '07-sponsored', '01-ambassador');
ALTER TABLE "_events_v" ALTER COLUMN "version_tier" SET DATA TYPE "public"."enum__events_v_version_tier" USING "version_tier"::"public"."enum__events_v_version_tier";
ALTER TABLE "locations" ALTER COLUMN "tier" SET DATA TYPE text;
UPDATE "locations" SET "tier" = '06-standard';
DROP TYPE "public"."enum_locations_tier";
CREATE TYPE "public"."enum_locations_tier" AS ENUM('05-new', '06-standard', '02-headline', '03-spotlight', '04-recommended', '07-sponsored', '01-ambassador');
ALTER TABLE "locations" ALTER COLUMN "tier" SET DATA TYPE "public"."enum_locations_tier" USING "tier"::"public"."enum_locations_tier";
ALTER TABLE "_locations_v" ALTER COLUMN "version_tier" SET DATA TYPE text;
UPDATE "_locations_v" SET "version_tier" = '06-standard';
DROP TYPE "public"."enum__locations_v_version_tier";
CREATE TYPE "public"."enum__locations_v_version_tier" AS ENUM('05-new', '06-standard', '02-headline', '03-spotlight', '04-recommended', '07-sponsored', '01-ambassador');
ALTER TABLE "_locations_v" ALTER COLUMN "version_tier" SET DATA TYPE "public"."enum__locations_v_version_tier" USING "version_tier"::"public"."enum__locations_v_version_tier";
ALTER TABLE "services" ALTER COLUMN "tier" SET DATA TYPE text;
UPDATE "services" SET "tier" = '06-standard';
DROP TYPE "public"."enum_services_tier";
CREATE TYPE "public"."enum_services_tier" AS ENUM('05-new', '06-standard', '02-headline', '03-spotlight', '04-recommended', '07-sponsored', '01-ambassador');
ALTER TABLE "services" ALTER COLUMN "tier" SET DATA TYPE "public"."enum_services_tier" USING "tier"::"public"."enum_services_tier";
ALTER TABLE "_services_v" ALTER COLUMN "version_tier" SET DATA TYPE text;
UPDATE "_services_v" SET "version_tier" = '06-standard';
DROP TYPE "public"."enum__services_v_version_tier";
CREATE TYPE "public"."enum__services_v_version_tier" AS ENUM('05-new', '06-standard', '02-headline', '03-spotlight', '04-recommended', '07-sponsored', '01-ambassador');
ALTER TABLE "_services_v" ALTER COLUMN "version_tier" SET DATA TYPE "public"."enum__services_v_version_tier" USING "version_tier"::"public"."enum__services_v_version_tier";
ALTER TABLE "events" ALTER COLUMN "last_viewed_at" SET DEFAULT '2025-12-18T09:50:10.357Z';
ALTER TABLE "_events_v" ALTER COLUMN "version_last_viewed_at" SET DEFAULT '2025-12-18T09:50:10.357Z';
ALTER TABLE "locations" ALTER COLUMN "last_viewed_at" SET DEFAULT '2025-12-18T09:50:10.357Z';
ALTER TABLE "_locations_v" ALTER COLUMN "version_last_viewed_at" SET DEFAULT '2025-12-18T09:50:10.357Z';
ALTER TABLE "services" ALTER COLUMN "last_viewed_at" SET DEFAULT '2025-12-18T09:50:10.357Z';
ALTER TABLE "_services_v" ALTER COLUMN "version_last_viewed_at" SET DEFAULT '2025-12-18T09:50:10.357Z';
ALTER TABLE "search" ADD COLUMN "rating" numeric;
ALTER TABLE "search" ADD COLUMN "tier" varchar;
ALTER TABLE "search" ADD COLUMN "views" numeric;
ALTER TABLE "search" ADD COLUMN "favorites_count" numeric;
ALTER TABLE "events" ALTER COLUMN "tier" SET DEFAULT '06-standard';
ALTER TABLE "events" ALTER COLUMN "last_viewed_at" SET DEFAULT '2025-12-18T11:13:18.001Z';
ALTER TABLE "_events_v" ALTER COLUMN "version_tier" SET DEFAULT '06-standard';
ALTER TABLE "_events_v" ALTER COLUMN "version_last_viewed_at" SET DEFAULT '2025-12-18T11:13:18.001Z';
ALTER TABLE "locations" ALTER COLUMN "tier" SET DEFAULT '06-standard';
ALTER TABLE "locations" ALTER COLUMN "last_viewed_at" SET DEFAULT '2025-12-18T11:13:18.001Z';
ALTER TABLE "_locations_v" ALTER COLUMN "version_tier" SET DEFAULT '06-standard';
ALTER TABLE "_locations_v" ALTER COLUMN "version_last_viewed_at" SET DEFAULT '2025-12-18T11:13:18.001Z';
ALTER TABLE "services" ALTER COLUMN "tier" SET DEFAULT '06-standard';
ALTER TABLE "services" ALTER COLUMN "last_viewed_at" SET DEFAULT '2025-12-18T11:13:18.001Z';
ALTER TABLE "_services_v" ALTER COLUMN "version_tier" SET DEFAULT '06-standard';
ALTER TABLE "_services_v" ALTER COLUMN "version_last_viewed_at" SET DEFAULT '2025-12-18T11:13:18.001Z